
import { CircuitReport, SimulationData } from '../../../types';
import { GoogleGenAI, Type } from "@google/genai";
import { apiKeyManager } from '../../../services/apiKeyManager';

const enhanceReportWithAI = async (
    sections: any,
    data: SimulationData | null
): Promise<any> => {
    let apiKey = apiKeyManager.getCurrentKey();
    if (!apiKey) apiKey = process.env.API_KEY;

    if (!apiKey) return sections;

    try {
        let ai = new GoogleGenAI({ apiKey });
        
        // Prepare Context
        const measurements = data?.measurements || {};
        const measurementStr = Object.entries(measurements)
            .map(([k, v]) => `${k}: ${v.toExponential(3)}`)
            .join(', ');
        
        const variablesStr = data?.variables?.join(', ') || 'None';
        const contextData = `
        CONTEXT DATA (SIMULATION RESULTS):
        - Measurements: [${measurementStr}]
        - Tracked Variables: [${variablesStr}]
        `;

        const enhancedSections: any = { ...sections };
        const sectionKeys = Object.keys(sections);

        for (const key of sectionKeys) {
            const content = sections[key];
            // Skip empty or non-string sections
            if (!content || typeof content !== 'string') continue;

            const prompt = `
            You are an expert Senior Electronics Engineer and Technical Editor.
            
            YOUR TASK:
            Enhance the content of the circuit analysis report section: "${key.toUpperCase()}".
            The draft content was generated by an automated checker. 
            Rewrite it to be more detailed, professional, and insightful, incorporating the provided raw simulation data where relevant.

            ${contextData}

            DRAFT CONTENT:
            "${content}"

            GUIDELINES:
            1. **Precision**: Check measurements and insert exact values.
            2. **Tone**: Professional engineering language.
            3. **Formatting**: Use Markdown.
            4. **Focus**: Focus ONLY on the "${key}" section. Do not add headers for other sections.
            5. **Output**: Return ONLY the enhanced text for this section.
            `;

            let success = false;
            while (!success) {
                try {
                    const response = await ai.models.generateContent({
                        model: 'gemma-3-27b-it',
                        contents: prompt,
                    });
                    
                    if (response.text) {
                        enhancedSections[key] = response.text;
                    }
                    success = true;
                } catch (error: any) {
                     if (error.status === 429 || error.message?.includes('429')) {
                         console.warn(`Rate limit hit for section ${key}`);
                         const newKey = apiKeyManager.rotateKey();
                         // If we have a new key, update and retry
                         if (newKey && newKey !== apiKey) {
                             apiKey = newKey;
                             ai = new GoogleGenAI({ apiKey });
                             continue;
                         }
                     }
                     // If not rate limit or no new key, log and skip this section
                     console.error(`Failed to enhance section ${key}:`, error);
                     break;
                }
            }
        }
        return enhancedSections;

    } catch (e) {
        console.error("AI Report Enhancement Failed:", e);
        return sections;
    }
};

export const handleSubmitCircuitReport = async (
    args: any,
    actions: { addReport: (r: CircuitReport) => void },
    simulationResults: SimulationData | null
) => {
    let sections = args.sections || {};

    console.log("Submitting report...", sections);

    // Apply AI Enhancement Layer
    // We do this server-side (or client-side here via SDK) before saving to make the report permanent and high-quality.
    sections = await enhanceReportWithAI(sections, simulationResults);

    const report: CircuitReport = {
        id: crypto.randomUUID(),
        timestamp: Date.now(),
        title: args.title || "Untitled Report",
        summary: args.summary || "No summary provided.",
        tags: args.tags || [],
        sections: {
            overall: sections.overall || "",
            problems: sections.problems || "",
            recommendations: sections.recommendations || "",
            warnings: sections.warnings || "",
            cautions: sections.cautions || ""
        },
        measurements: simulationResults?.measurements || {},
        simulationData: simulationResults || undefined // Capture full data for graphs
    };

    actions.addReport(report);

    return { 
        message: "Report generated, enhanced by AI, and saved successfully.",
        reportId: report.id,
        link: "View in Report History"
    };
};
